export const MOCK_USER = {
  name: "김민수",
  role: "장로",
  district: "1구역",
  group: "1조",
  birthdate: "1972.04.18",
  phone: "010-2341-7782",
  email: "minsoo.kim@example.com",
  address: "서울특별시 영등포구",
  registeredDate: "2014.03.09",
  baptismDate: "2002.05.19",
};

export const MOCK_DEPT = {
  position: "장로",
  department: "남선교회 1지회",
  duty: "안내위원장",
  district: "1구역",
  group: "1조",
  ordainedDate: "2021.03.07",
};

export const MOCK_GROUPS = [
  { id: 1, name: "1구역 모임", info: "매주 화요일 19:30 · 옥길동 · 구역원 · 총 8명" },
  { id: 2, name: "1조", info: "매주 토요일 20:00 · 본당 4층 · 리더 · 총 6명" },
  { id: 3, name: "남선교회 1지회", info: "월 1회 셋째 주 · 안내위원장 · 총 24명" },
  { id: 4, name: "성가대 (테너)", info: "매주 금요일 20:00 · 본당 4층 · 단원 · 총 18명" },
];

export const INITIAL_SCHEDULES = [
  {
    id: 1,
    date: "02.18",
    day: "화",
    title: "1구역 모임",
    info: "옥길동 박OO 권사 댁 · 19:30",
    status: "참석 예정",
  },
  {
    id: 2,
    date: "02.22",
    day: "토",
    title: "성가대 부활절 연습",
    info: "본당 4층 · 20:00",
    status: "미정",
  },
  {
    id: 3,
    date: "02.23",
    day: "주",
    title: "주일 1·2부 예배",
    info: "본당 · 09:00 / 11:00",
    status: "참석 예정",
  },
  {
    id: 4,
    date: "02.25",
    day: "화",
    title: "개인 — 직장 송별회",
    info: "강남 · 19:00",
    status: "참석 예정",
  },
  {
    id: 5,
    date: "04.05",
    day: "주",
    title: "부활주일 연합 예배",
    info: "본당 · 11:00",
    status: "참석 예정",
  },
  {
    id: 6,
    date: "04.12",
    day: "주",
    title: "주일 1부 예배",
    info: "본당 · 09:00",
    status: "참석 예정",
  },
  {
    id: 7,
    date: "04.15",
    day: "화",
    title: "1구역 모임",
    info: "옥길동 박OO 권사 댁 · 19:30",
    status: "미정",
  },
  {
    id: 8,
    date: "04.19",
    day: "토",
    title: "성가대 정기연습",
    info: "본당 4층 · 20:00",
    status: "참석 예정",
  },
  {
    id: 9,
    date: "04.27",
    day: "주",
    title: "어린이주일 연합예배",
    info: "본당 · 10:30",
    status: "참석 예정",
  },
  {
    id: 10,
    date: "05.04",
    day: "주",
    title: "주일 2부 예배",
    info: "본당 · 11:00",
    status: "참석 예정",
  },
  { id: 11, date: "05.06", day: "화", title: "1구역 심방", info: "옥길동 · 19:00", status: "미정" },
  {
    id: 12,
    date: "05.18",
    day: "주",
    title: "오순절 기념 예배",
    info: "본당 · 11:00",
    status: "참석 예정",
  },
];

export const INITIAL_PRAYERS = [
  {
    id: 1,
    type: "기도",
    title: "가정 회복을 위한 기도",
    content: "가족 간의 깊은 대화가 필요합니다. 함께 기도해 주세요.",
    date: "2026.02.10",
    status: "답변 완료",
    reply:
      "김OO 목사 — 가정을 향한 하나님의 회복을 함께 기도합니다. 화요일 심방 일정 잡아드리겠습니다.",
  },
  {
    id: 2,
    type: "상담",
    title: "진로 상담 요청",
    content: "이직 결정을 앞두고 지혜가 필요합니다.",
    date: "2026.02.04",
    status: "답변 대기",
    reply: null,
  },
  {
    id: 3,
    type: "기도",
    title: "건강 회복 감사",
    content: "수술 잘 끝났습니다. 함께 기도해 주신 모든 분께 감사드립니다.",
    date: "2026.01.27",
    status: "답변 완료",
    reply: "이OO 부목사 — 회복의 은혜를 함께 기뻐합니다. 다음 주 새벽기도 함께 나누면 좋겠습니다.",
  },
  {
    id: 4,
    type: "기도",
    title: "자녀 입시를 위한 기도",
    content: "큰 아이가 수능을 앞두고 있습니다. 지혜와 평안을 위해 기도 부탁드립니다.",
    date: "2026.01.15",
    status: "답변 완료",
    reply: "김OO 목사 — 시험 기간 내내 함께 기도하겠습니다.",
  },
  {
    id: 5,
    type: "상담",
    title: "부부 갈등 상담 요청",
    content: "가정 내 갈등으로 힘든 시간을 보내고 있습니다. 상담을 부탁드립니다.",
    date: "2026.01.08",
    status: "답변 완료",
    reply: "이OO 부목사 — 이번 주 금요일 저녁에 시간을 내겠습니다.",
  },
  {
    id: 6,
    type: "기도",
    title: "직장 문제를 위한 기도",
    content: "새 직장을 구하고 있습니다. 좋은 길이 열리도록 기도해 주세요.",
    date: "2025.12.20",
    status: "답변 대기",
    reply: null,
  },
  {
    id: 7,
    type: "상담",
    title: "신앙 고민 상담",
    content: "믿음이 흔들리는 시기입니다. 말씀으로 도움받고 싶습니다.",
    date: "2025.12.05",
    status: "답변 완료",
    reply: "김OO 목사 — 언제든지 연락 주세요. 함께 말씀 나누겠습니다.",
  },
];

export const INITIAL_INQUIRIES = [
  {
    id: 1,
    title: "교적 정보 수정 요청 (주소 변경)",
    date: "2026.02.12",
    status: "답변 완료",
    reply: "사무국 — 주소 변경 완료되었습니다. 다음 주보부터 반영됩니다.",
  },
  { id: 2, title: "새가족부 신청", date: "2026.02.05", status: "진행 중", reply: null },
  {
    id: 3,
    title: "심방 일정 요청",
    date: "2026.01.20",
    status: "답변 완료",
    reply: "부목사 — 2/3 화요일 19:00에 방문드리겠습니다.",
  },
  {
    id: 4,
    title: "교육 프로그램 등록",
    date: "2026.01.10",
    status: "답변 완료",
    reply: "교육부 — 제자훈련 1기 등록 완료되었습니다.",
  },
  {
    id: 5,
    title: "성가대 악보 신청",
    date: "2025.12.28",
    status: "답변 완료",
    reply: "사무국 — 악보 준비되었습니다. 연습 전 수령해 주세요.",
  },
  {
    id: 6,
    title: "헌금 영수증 발급 요청",
    date: "2025.12.15",
    status: "답변 완료",
    reply: "사무국 — 이메일로 발송드렸습니다.",
  },
  { id: 7, title: "구역 변경 신청", date: "2025.11.30", status: "진행 중", reply: null },
  {
    id: 8,
    title: "봉사 일정 문의",
    date: "2025.11.20",
    status: "답변 완료",
    reply: "사무국 — 다음 달 봉사 일정표를 공유드렸습니다.",
  },
];
